services:
  certbot:
    image: anarchist117/certbot
    container_name: certbot
    restart: always
    ports:
      - 80:80
    volumes:
      - ./letsencrypt/:/etc/letsencrypt
    environment:
      - DOMAIN=vpn.domain.com
      - EMAIL=admin@vpn.domain.com
