certbot:
    image: anarchist117/certbot
    container_name: certbot
    restart: always
    ports:
      - 80:80
    volumes:
      - ./letsencrypt/:/etc/letsencrypt
    entrypoint: certonly --standalone -d test.domain.com -m admin@domain.com --non-interactive --agree-tos
