services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - 0.0.0.0:80:80
    volumes:
      - /path/to/speedtest-tracker/data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DISPLAY_TIMEZONE=Etc/UTC
      - APP_KEY=   # Copy from https://speedtest-tracker.dev/
      - DB_CONNECTION=sqlite
      - PRUNE_RESULTS_OLDER_THAN=365
      - SPEEDTEST_SCHEDULE=0 * * * *
      - SPEEDTEST_SERVERS=
      - PUBLIC_DASHBOARD=True
      - APP_URL=http://tracker.yourdomain.com
      - TELEGRAM_BOT_TOKEN=BOT_TOKEN
