services:

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    command: >
      /bin/sh -c "certbot certonly --standalone -d ${DOMAIN} -m ${EMAIL} --non-interactive --agree-tos &&
        while :; do
          certbot renew
          sleep 12h
        done"

  ocserv:
    image: anarchist117/openconnect
    container_name: openconnect
    restart: always
    ports:
      - '443:443'
    volumes:
      - ./ocserv:/etc/ocserv
      - ./letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/ocserv/le/server.pem:ro
      - ./letsencrypt/live/${DOMAIN}/privkey.pem:/etc/ocserv/le/server.key:ro
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    privileged: true
    command: >
      sh -c "iptables -t nat -A POSTROUTING -j MASQUERADE &&
      iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu &&
      exec ocserv -d 3 -c /etc/ocserv/ocserv.conf -f"
