services:
  ocserv:
    image: ocserv
    container_name: ocserv
    restart: always
    ports:
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./ocserv/letsencrypt/live/vpn.domain.com/fullchain.pem:/etc/ocserv/server-cert.pem:ro
      - ./ocserv/letsencrypt/live/vpn.domain.com/privkey.pem:/etc/ocserv/server-key.pem:ro
      - ./ocserv/ocserv.conf:/etc/ocserv/ocserv.conf:ro

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./ocserv/letsencrypt/:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
