services:

  certbot:
    image: anarchist117/certbot
    container_name: certbot
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./letsencrypt/:/etc/letsencrypt
    command: certonly --standalone -d ${DOMAIN} -m ${EMAIL} --non-interactive --agree-tos
    environment:
      - DOMAIN=vpn.domain.com
      - EMAIL=admin@domain.com

  ocserv:
    image: anarchist117/ocserv
    container_name: ocserv
    restart: always
    ports:
      - '443:443'
    volumes:
      - ./ocserv:/etc/ocserv:rw
      - ./letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/ocserv/le/server.pem:ro
      - ./letsencrypt/live/${DOMAIN}/privkey.pem:/etc/ocserv/le/server.key:ro
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    privileged: true
    environment:
      - DOMAIN=vpn.domain.com
      - CA_Name="SSL VPN"      
