services:

  certbot:
    image: anarchist117/certbot
    container_name: certbot
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./letsencrypt/:/etc/letsencrypt
    environment:
      - DOMAIN=vpn.domain.com
      - EMAIL=admin@domain.com

  ocserv:
    image: anarchist117/ocserv
    container_name: ocserv
    restart: always
    ports:
      - '443:443'
    volumes:
      - ./ocserv:/etc/ocserv
      - ./letsencrypt/:/etc/ocserv/le:ro
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    privileged: true
    environment:
      - Domain=vpn.domain.com  # CA Organization (VPN Domain)
      - CA_Name="SSL VPN"      # CA Name (Root CA)
      - Expiration=365         # User certificate expiration days
