services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime
    restart: always
    ports:
      - 0.0.0.0:3001:3001
    volumes:
      - uptime-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Europe/Moscow
      - UMASK=0022
      - UPTIME_KUMA_DB_TYPE=mariadb
      - UPTIME_KUMA_DB_HOSTNAME=mariadb
      - UPTIME_KUMA_DB_PORT=3306
      - UPTIME_KUMA_DB_NAME=kuma
      - UPTIME_KUMA_DB_USERNAME=kuma
      - UPTIME_KUMA_DB_PASSWORD=kuma
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:lts
    container_name: uptime-mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - "mariadb-data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MARIADB_USER=kuma
      - MARIADB_PASSWORD=kuma
      - MARIADB_DATABASE=kuma
      - MARIADB_ROOT_PASSWORD=password

volumes:
  mariadb-data:
    name: "mariadb-data"
  uptime-data:
    name: "uptime-data"